Add filtering capabilities to microservice
cuappdev/volume-microservice pull request #12
Opened 2022-02-12 06:54 UTC by kidzegeye

Set up filtering by keywords that checks article titles and bodies. Sets the `filtered` field to `true` if there is a match.

2022-02-15 16:31 UTC, dishanest approved these changes

2022-02-17 20:02 UTC, katesliang approved these changes
Good job!

2022-02-17 21:31 UTC, alanna-zhou requested changes
nice! some changes requested~

2022-02-17 21:31 UTC, alanna-zhou commented on src/article.py
> +    def isProfane(self):
python functions should always follow this convention `is_profane()`

2022-02-17 21:31 UTC, alanna-zhou commented on src/article.py
> +        return pf.contains_profanity(self.entry.title) or check_content
do not use try excepts -- this isn't an ideal situation to be in -- you should instead use `.get` or catch more specific exceptions

2022-02-17 21:31 UTC, alanna-zhou commented on src/article.py
> +        check_content = False
if this is a bool, should be more descriptive, usually starting with "is": `is_content_checked`

2022-02-20 00:13 UTC, chalo2000 approved these changes
LGTM, just resolve @alanna-zhou's comments and we can merge this.

2022-02-25 01:48 UTC, closed without merging